project:
  type: website

website:
  title: "MO NOROUZI"
  image: C:\Users\mstto\quarto_website.image.jpeg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - contact.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



